-- IT'S IMPORTANT TO RESTART PK AUTOINCREMENT OTHERWISE IT WOULDN'T RESET ITSELF
SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE UTENTE_RUOLO RESTART IDENTITY;
TRUNCATE TABLE CORSA RESTART IDENTITY;
TRUNCATE TABLE AUTISTA RESTART IDENTITY;
TRUNCATE TABLE CLIENTE RESTART IDENTITY;
TRUNCATE TABLE VEICOLO RESTART IDENTITY;
TRUNCATE TABLE UTENTE RESTART IDENTITY;
TRUNCATE TABLE RUOLO RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;